#!/bin/bash
#
# Auto-configure Chrony with Jimmy Paputto GNSS HAT
#

set -e

echo "=============================================="
echo "Chrony + JP GNSS2GPSD Bridge Auto Configuration"
echo "=============================================="

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "❌ ERROR: This script must be run as root (use sudo)"
   echo "   Usage: sudo ./configure_chrony.sh [--with-pps]"
   exit 1
fi

USE_PPS=false
if [[ "$1" == "--with-pps" ]]; then
    USE_PPS=true
    echo "🔔 Configuring Chrony with PPS support"
else
    echo "📡 Configuring Chrony without PPS"
fi

# Check if gpsd is configured
if ! systemctl is-enabled jpgnss2gpsd-bridge &>/dev/null; then
    echo "⚠️  WARNING: jpgnss2gpsd-bridge is not enabled"
    echo "   Run first: sudo ./scripts/configure_gpsd.sh"
fi

# Remove ntp if present (conflict)
if systemctl is-active --quiet ntp 2>/dev/null; then
    echo "🔄 Removing ntp (conflicts with chrony)..."
    systemctl stop ntp
    systemctl disable ntp
    apt-get remove ntp -y
fi

# Install chrony
echo "📦 Installing Chrony..."
apt-get update
apt-get install -y chrony

# Backup original config
if [ ! -f /etc/chrony/chrony.conf.backup ]; then
    cp /etc/chrony/chrony.conf /etc/chrony/chrony.conf.backup
    echo "💾 Backed up original chrony.conf"
fi

# Create Chrony configuration
echo "⚙️  Configuring Chrony..."

if [ "$USE_PPS" = true ]; then
    # Check if PPS device exists
    if [ ! -c "/dev/pps0" ]; then
        echo "⚠️  WARNING: /dev/pps0 not found. PPS may not work."
    fi
    
    cat > /etc/chrony/chrony.conf << 'EOF'
# Jimmy Paputto GNSS HAT + PPS Configuration
# Generated by configure_chrony.sh

# GPS time via SHM from gpsd
refclock SHM 0 offset 0.0 delay 0.2 refid NMEA

# PPS (ultra-precise timing)
refclock PPS /dev/pps0 refid PPS lock NMEA

# Fallback internet time servers
pool 0.pool.ntp.org iburst
pool 1.pool.ntp.org iburst
pool 2.pool.ntp.org iburst

# Local network access (adjust for your network) for example
# allow 192.168.0.0/16

# Performance tuning for GNSS
maxupdateskew 100.0
makestep 1000 3
rtcsync

# Improved accuracy settings
maxchange 1000 1 2
corrtimeratio 100

# Logging and statistics
log tracking measurements statistics
logdir /var/log/chrony
logchange 0.1

# RTC synchronization
rtconutc
EOF
else
    cat > /etc/chrony/chrony.conf << 'EOF'
# Jimmy Paputto GNSS HAT Configuration (GPS only)
# Generated by configure_chrony.sh

# GPS time via SHM from gpsd
refclock SHM 0 offset 0.0 delay 0.2 refid NMEA

# Fallback internet time servers
pool 0.pool.ntp.org iburst
pool 1.pool.ntp.org iburst
pool 2.pool.ntp.org iburst

# Local network access (adjust for your network) for example
# allow 192.168.0.0/16

# Performance tuning for GNSS
maxupdateskew 100.0
makestep 1000 3
rtcsync

# Improved accuracy settings
maxchange 1000 1 2

# Logging and statistics
log tracking measurements statistics
logdir /var/log/chrony
logchange 0.1

# RTC synchronization
rtconutc
EOF
fi

# Create log directory
mkdir -p /var/log/chrony

# Set proper ownership (chrony user may have different name on different systems)
if id "chrony" &>/dev/null; then
    chown chrony:chrony /var/log/chrony
elif id "_chrony" &>/dev/null; then
    chown _chrony:_chrony /var/log/chrony
elif id "chronyd" &>/dev/null; then
    chown chronyd:chronyd /var/log/chrony
else
    # Fallback to root if chrony user doesn't exist
    echo "⚠️  WARNING: chrony user not found, using root ownership"
    chown root:root /var/log/chrony
    chmod 755 /var/log/chrony
fi

# Check if chrony service is masked and unmask if needed
if systemctl status chrony 2>&1 | grep -q "masked"; then
    echo "🔓 Unmasking chrony service..."
    systemctl unmask chrony
fi

# Enable and restart chrony
echo "🚀 Starting Chrony service..."
systemctl enable chrony
systemctl restart chrony

# Wait a moment for startup
sleep 3

echo ""
echo "🎉 Chrony configuration completed successfully!"
echo ""
echo "Configuration:"
echo "  Config file: /etc/chrony/chrony.conf"
echo "  Backup: /etc/chrony/chrony.conf.backup"
echo "  Logs: /var/log/chrony/"
echo ""
echo "Status commands:"
echo "  chronyc sources -v   # Show time sources"
echo "  chronyc tracking     # Show sync status"
echo "  chronyc sourcestats  # Show source stats"
echo ""
if [ "$USE_PPS" = true ]; then
    echo "Expected output from 'chronyc sources -v':"
    echo "  #* GPS - GPS time source (synced)"
    echo "  #* PPS - PPS signal (preferred)"
    echo ""
fi
echo "To monitor:"
echo "  watch -n 1 'chronyc tracking'"
