#!/bin/bash
#
# Auto-configure NTP with Jimmy Paputto GNSS HAT
#

set -e

echo "=============================================="
echo "NTP + JP GNSS2GPSD Bridge Auto Configuration"
echo "=============================================="

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo "❌ ERROR: This script must be run as root (use sudo)"
   echo "   Usage: sudo ./configure_ntp.sh [--with-pps]"
   exit 1
fi

USE_PPS=false
if [[ "$1" == "--with-pps" ]]; then
    USE_PPS=true
    echo "🔔 Configuring NTP with PPS support"
else
    echo "📡 Configuring NTP without PPS"
fi

# Check if gpsd is configured
if ! systemctl is-enabled jpgnss2gpsd-bridge &>/dev/null; then
    echo "⚠️  WARNING: jpgnss2gpsd-bridge is not enabled"
    echo "   Run first: sudo ./scripts/configure_gpsd.sh"
fi

# Remove chrony if present (conflict)
if systemctl is-active --quiet chronyd 2>/dev/null; then
    echo "🔄 Removing chrony (conflicts with ntp)..."
    systemctl stop chronyd
    systemctl disable chronyd
    apt-get remove chrony -y
fi

# Install ntp
echo "📦 Installing NTP..."
apt-get update
apt-get install -y ntp

# Backup original config
if [ ! -f /etc/ntp.conf.backup ]; then
    cp /etc/ntp.conf /etc/ntp.conf.backup
    echo "💾 Backed up original ntp.conf"
fi

# Create NTP configuration
echo "⚙️  Configuring NTP..."

if [ "$USE_PPS" = true ]; then
    # Check if PPS device exists
    if [ ! -c "/dev/pps0" ]; then
        echo "⚠️  WARNING: /dev/pps0 not found. PPS may not work."
    fi
    
    cat > /etc/ntp.conf << 'EOF'
# Jimmy Paputto GNSS HAT + PPS Configuration
# Generated by configure_ntp.sh

# Use local GPS time via gpsd shared memory (SHM 0)
server 127.127.28.0 minpoll 4 maxpoll 4
fudge 127.127.28.0 time1 0.420 refid GPS stratum 1

# Use PPS signal for high precision timing (SHM 1)
server 127.127.22.0 minpoll 4 maxpoll 4 prefer
fudge 127.127.22.0 refid PPS stratum 0

# Fallback internet time servers
pool 0.pool.ntp.org iburst
pool 1.pool.ntp.org iburst
pool 2.pool.ntp.org iburst

# Security and access control
restrict default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict ::1
restrict 192.168.0.0 mask 255.255.0.0 nomodify notrap

# Statistics and logging
statsdir /var/log/ntpstats/
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable

# Drift file
driftfile /var/lib/ntp/ntp.drift
EOF
else
    cat > /etc/ntp.conf << 'EOF'
# Jimmy Paputto GNSS HAT Configuration (GPS only)
# Generated by configure_ntp.sh

# Use local GPS time via gpsd shared memory
server 127.127.28.0 minpoll 4 maxpoll 4
fudge 127.127.28.0 time1 0.420 refid GPS stratum 1

# Fallback internet time servers
pool 0.pool.ntp.org iburst
pool 1.pool.ntp.org iburst
pool 2.pool.ntp.org iburst

# Security and access control
restrict default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict ::1
restrict 192.168.0.0 mask 255.255.0.0 nomodify notrap

# Statistics and logging
statsdir /var/log/ntpstats/
statistics loopstats peerstats clockstats
filegen loopstats file loopstats type day enable
filegen peerstats file peerstats type day enable
filegen clockstats file clockstats type day enable

# Drift file
driftfile /var/lib/ntp/ntp.drift
EOF
fi

# Create stats directory
mkdir -p /var/log/ntpstats

# Set proper ownership (ntp user may have different name on different systems)
if id "ntp" &>/dev/null; then
    chown ntp:ntp /var/log/ntpstats
elif id "_ntp" &>/dev/null; then
    chown _ntp:_ntp /var/log/ntpstats
elif id "ntpd" &>/dev/null; then
    chown ntpd:ntpd /var/log/ntpstats
else
    # Fallback to root if ntp user doesn't exist
    echo "⚠️  WARNING: ntp user not found, using root ownership"
    chown root:root /var/log/ntpstats
    chmod 755 /var/log/ntpstats
fi

# Check if ntp service is masked and unmask if needed
if systemctl status ntp 2>&1 | grep -q "masked"; then
    echo "🔓 Unmasking ntp service..."
    systemctl unmask ntp
fi

# Enable and restart ntp
echo "🚀 Starting NTP service..."
systemctl enable ntp
systemctl restart ntp

# Wait a moment for startup
sleep 3

echo ""
echo "🎉 NTP configuration completed successfully!"
echo ""
echo "Configuration:"
echo "  Config file: /etc/ntp.conf"
echo "  Backup: /etc/ntp.conf.backup"
echo "  Stats: /var/log/ntpstats/"
echo ""
echo "Status commands:"
echo "  ntpq -p              # Show peers"
echo "  ntpq -c rv           # Show system variables"
echo "  ntpstat              # Quick status"
echo ""
if [ "$USE_PPS" = true ]; then
    echo "Expected output from 'ntpq -p':"
    echo "  *GPS(0)   - GPS time source (active)"
    echo "  oPPS(0)   - PPS signal (PPS peer)"
    echo ""
fi
echo "To monitor:"
echo "  watch -n 1 'ntpq -p'"
